# Generated by Django 4.2.30 on 2026-04-25 10:38

import blog.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=70, scale=0.5, size=[500, 500], upload_to=blog.models.upload_to_callable, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.CharField(max_length=250, null=True, verbose_name='Job'),
        ),
    ]
