# Generated by Django 4.2.30 on 2026-04-25 11:31

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_account_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=70, scale=0.5, size=[500, 500], upload_to='account_images', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Job'),
        ),
    ]
