# Generated by Django 4.2.30 on 2026-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_account_image_file_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Prog', 'Programming'), ('AI', 'Artificial Intelligence'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
