# Generated by Django 4.2.30 on 2026-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Celebrity', 'Celebrity'), ('Cartoon', 'Cartoon'), ('Admin', 'Admin'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
