# Generated by Django 4.2.30 on 2026-04-20 18:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_created_1ba45b_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default=blog.models.upload_to_callable, max_length=250, null=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='blog_image_created_a116df_idx'),
        ),
    ]
