# Generated by Django 4.2.30 on 2026-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_account_bio_alter_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-image_file']},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_created_a116df_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-image_file'], name='blog_image_image_f_00ae73_idx'),
        ),
    ]
