# Generated by Django 4.2.30 on 2026-04-25 13:40

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_file']},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_image_f_00ae73_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[1000, 1000], upload_to='account_images'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_file'], name='blog_image_image_f_a4e5b5_idx'),
        ),
    ]
