# Generated by Django 4.2.30 on 2026-04-25 13:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=70, scale=0.5, size=[1000, 1000], upload_to='account_images', verbose_name='Profile Image'),
        ),
    ]
