# Generated by Django 4.2.29 on 2026-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comment_body_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
